name: gameengine-server
version: 0.1.0.0
github: "seckujdivad/gameengine"
author: "David Juckes"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Server for gameengine

dependencies:
- base >= 4.7 && < 5
- network >= 3.1.1 && < 3.1.2
- bytestring
- stm >= 2.5
- containers >= 0.6 && < 0.7
- binary >= 0.8 && < 0.9
- aeson >= 1.5 && < 1.6
- directory >= 1.3 && < 1.4
- text >= 1.2 && < 1.3
- filepath >= 1.4 && < 1.5
- linear >= 1.21 && < 1.22
- bytestring-lexing >= 0.5 && < 0.6
- unordered-containers >= 0.2 && < 0.3

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns

executables:
  gameengine-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    dependencies:
    - gameengine-server

tests:
  gameengine-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameengine-server
