#pragma once

const int GAMEENGINE_NUM_DATA_TEX = 1;

const int GAMEENGINE_NORMAL_PASSTHROUGH_TEX = 4;

const float GAMEENGINE_NORMAL_POINTLIGHT_ATTENUATION_A = 0.032f;
const float GAMEENGINE_NORMAL_POINTLIGHT_ATTENUATION_B = 0.09f;
const float GAMEENGINE_NORMAL_POINTLIGHT_ATTENUATION_C = 1.0f;