#ifndef _RESOURCE_H
#define _RESOURCE_H

//100 - 199 reserved for custom types
#define RCT_TEXTFILE 100

//300+ reserved for identifiers
#define RCID_TF_POSTPROCESS_FRAGSHADER 300
#define RCID_TF_POSTPROCESS_VERTSHADER 301

#define RCID_TF_MODEL_FRAGSHADER 302
#define RCID_TF_MODEL_VERTSHADER 303

#define RCID_TF_MODEL_SHADOW_FRAGSHADER 304
#define RCID_TF_MODEL_SHADOW_VERTSHADER 305
#define RCID_TF_MODEL_SHADOW_GEOMSHADER 306

#endif
