#ifndef _RESOURCE_H
#define _RESOURCE_H

//100 - 199 reserved for custom types
#define RCT_TEXTFILE 100

//300+ reserved for identifiers
#define RCID_TF_POSTPROCESS_FRAGSHADER 300
#define RCID_TF_POSTPROCESS_VERTSHADER 301

#define RCID_TF_MODEL_NORMAL_FRAGSHADER 302
#define RCID_TF_MODEL_WIREFRAME_FRAGSHADER 303

#define RCID_TF_MODEL_VERTSHADER 304

#define RCID_TF_MODEL_SHADOW_FRAGSHADER 305
#define RCID_TF_MODEL_SHADOW_VERTSHADER 306

#define RCID_TF_MODEL_NORMAL_GEOMSHADER 307
#define RCID_TF_MODEL_WIREFRAME_GEOMSHADER 308
#define RCID_TF_MODEL_SHADOW_GEOMSHADER 309

#define RCID_TF_DEFAULT_FRAGSHADER 310
#define RCID_TF_DEFAULT_VERTSHADER 311

#endif
